-- The 12 tapes the web-portal renders today (web-portal/src/data/tapes.ts), so a
-- fresh database matches what the frontend already shows. Safe to re-run: a slug
-- that is already present is left untouched.
INSERT INTO tapes (id, slug, title, subtitle, year, genre, duration, rating, description,
                   color_primary, color_secondary, color_accent, color_label, pattern)
VALUES
       (gen_random_uuid(), 'neon-nights', 'NEON NIGHTS', 'The City Never Sleeps', '1987',
        'Action', '1h 54min', 'R',
        'A rogue detective navigates the neon-lit streets of a dystopian metropolis to uncover a conspiracy that reaches the highest levels of power.',
        '#ff006e', '#8338ec', '#ffbe0b', '#1a1a2e', 'stripes'),
       (gen_random_uuid(), 'chrome-horizon', 'CHROME HORIZON', 'Beyond the Last Frontier', '1984',
        'Sci-Fi', '2h 12min', 'PG-13',
        'In the year 2099, a crew of space pioneers embarks on a journey to the edge of the known universe aboard the starship Horizon.',
        '#00b4d8', '#0077b6', '#90e0ef', '#023e8a', 'gradient'),
       (gen_random_uuid(), 'velvet-thunder', 'VELVET THUNDER', NULL, '1989',
        'Thriller', '1h 38min', 'R',
        'A jazz musician stumbles into the criminal underworld when she witnesses a murder at an underground club in downtown Los Angeles.',
        '#9b5de5', '#f15bb5', '#fee440', '#240046', 'geometric'),
       (gen_random_uuid(), 'solar-burn', 'SOLAR BURN', 'No Escape from the Heat', '1986',
        'Action', '1h 47min', 'R',
        'When a solar flare knocks out the power grid, an ex-military survivalist must protect a small desert town from marauding raiders.',
        '#ff7b00', '#ff0000', '#ffdd00', '#3d0000', 'retro-blocks'),
       (gen_random_uuid(), 'midnight-frequency', 'MIDNIGHT FREQUENCY', NULL, '1991',
        'Horror', '1h 32min', 'R',
        'A late-night radio host begins receiving mysterious signals that predict horrifying events — events that only she can prevent.',
        '#2d00f7', '#6a00f4', '#e500a4', '#0a0a23', 'waves'),
       (gen_random_uuid(), 'turbo-kid', 'TURBO KID', 'Full Speed Ahead', '1988',
        'Adventure', '1h 42min', 'PG',
        'A teenage BMX champion discovers a hidden portal to a radical dimension where he must race against time to save both worlds.',
        '#00f5d4', '#00bbf9', '#f15bb5', '#0b132b', 'stripes'),
       (gen_random_uuid(), 'steel-rain', 'STEEL RAIN', NULL, '1985',
        'War', '2h 05min', 'R',
        'In the trenches of a futuristic battlefield, a platoon of mech-suit soldiers fights for survival against an unstoppable enemy force.',
        '#606c38', '#283618', '#dda15e', '#1b1b1b', 'diamonds'),
       (gen_random_uuid(), 'crystal-palace', 'CRYSTAL PALACE', 'A World of Wonder', '1990',
        'Fantasy', '1h 56min', 'PG',
        'A young girl discovers a magical crystal that transports her to an enchanted kingdom, where she must restore the balance of light and shadow.',
        '#d4a5ff', '#a855f7', '#67e8f9', '#1e1b4b', 'geometric'),
       (gen_random_uuid(), 'red-line', 'RED LINE', NULL, '1983',
        'Crime', '1h 49min', 'R',
        'An undercover cop infiltrates a ruthless street racing syndicate, but the deeper she goes, the harder it becomes to remember which side she''s on.',
        '#dc2626', '#991b1b', '#fbbf24', '#1c1917', 'retro-blocks'),
       (gen_random_uuid(), 'phantom-signal', 'PHANTOM SIGNAL', 'They Are Listening', '1992',
        'Sci-Fi', '1h 44min', 'PG-13',
        'Scientists at a remote radio telescope pick up an alien signal that seems to contain a warning — but decoding it may already be too late.',
        '#06d6a0', '#118ab2', '#ef476f', '#073b4c', 'waves'),
       (gen_random_uuid(), 'desert-mirage', 'DESERT MIRAGE', NULL, '1986',
        'Western', '2h 01min', 'PG-13',
        'A lone drifter rides into a ghost town on the edge of the Mojave, searching for a legendary treasure that may not even exist.',
        '#e9c46a', '#f4a261', '#e76f51', '#264653', 'gradient'),
       (gen_random_uuid(), 'black-ice', 'BLACK ICE', 'Cold-Blooded Justice', '1993',
        'Thriller', '1h 51min', 'R',
        'A forensic investigator in Anchorage tracks a serial killer whose victims are only found when the spring thaw reveals what winter buried.',
        '#94a3b8', '#475569', '#38bdf8', '#0f172a', 'diamonds')
ON CONFLICT (slug) DO NOTHING;
